/**
 * AUTO-GENERATED by extension/scripts/nls-coverage.mjs — DO NOT EDIT BY HAND.
 * Regenerate with: npm run generate:nls-coverage
 *
 * Manifest NLS value-coverage snapshot (plan 75 §2). `NLS_COVERAGE` maps each
 * translated locale to the percent of the 259 manifest keys whose value
 * differs from English. English is the source (always 100%) and is not listed.
 * Consumed by the future activation coverage notice; guarded for staleness by
 * `npm run verify:nls-coverage`.
 */

export const NLS_TOTAL_KEYS = 259;

/** Translated-locale → percent of manifest values that differ from English (0–100). */
export const NLS_COVERAGE: Record<string, number> = {};
