/**
 * Host-panel English source strings — Dashboard panel family. Plan 75 §3.1.
 *
 * Covers five host-built webview panels that share this registry slice:
 *   - Dashboard            ([../dashboard/dashboard-html.ts](../dashboard/dashboard-html.ts))
 *   - Report               ([../report/report-html.ts](../report/report-html.ts))
 *   - Size Analytics       ([../analytics/size-html.ts](../analytics/size-html.ts))
 *   - Column Profiler      ([../profiler/profiler-html.ts](../profiler/profiler-html.ts))
 *   - Performance Baselines ([../debug/perf-baseline-html.ts](../debug/perf-baseline-html.ts))
 *
 * One registry slice per panel family (see `HOST_STRING_REGISTRIES` in
 * [../l10n.ts](../l10n.ts)). Each entry maps a SYMBOLIC KEY → its ENGLISH text;
 * the panel's HTML builder resolves the key via `t()` so the string reaches the
 * translation pipeline instead of shipping English in every locale.
 *
 * Runtime values (counts, byte sizes, table names, durations) are passed as
 * `{0}`/`{1}` tokens, never concatenated English — `vscode.l10n.t()` substitutes
 * them so a translator can reorder the sentence. Pure data (numbers, formatted
 * byte strings, SQL, grades) stays rendered from the source objects directly and
 * is NOT a catalog string.
 *
 * Client-script strings inside each panel's `<script>…</script>` are NOT in this
 * slice; those run in the webview without host `t()` and are tagged with a
 * `// TODO(l10n): client-script string` marker at their call site.
 */

/** Symbolic key → English source text for the dashboard panel family. */
export const stringsPanelDashboard: Record<string, string> = {
  // --- Dashboard: header chrome ---
  'panel.dashboard.title': 'Dashboard',
  'panel.dashboard.btn.addWidget': 'Add Widget',
  'panel.dashboard.btn.layout': 'Layout',
  'panel.dashboard.btn.refresh': 'Refresh',

  // --- Dashboard: empty state ---
  'panel.dashboard.empty.title': 'No widgets yet.',
  // "+ Add Widget" names the literal button label the user clicks; kept inside
  // the quotes so the whole instruction reads as one translatable sentence.
  'panel.dashboard.empty.hint': 'Click "+ Add Widget" to get started.',

  // --- Dashboard: add-widget modal ---
  'panel.dashboard.addModal.title': 'Add Widget',

  // --- Dashboard: configure-widget modal ---
  'panel.dashboard.configModal.title': 'Configure Widget',
  'panel.dashboard.configModal.save': 'Save',
  'panel.dashboard.configModal.cancel': 'Cancel',

  // --- Dashboard: manage-layouts modal ---
  'panel.dashboard.layoutModal.title': 'Manage Layouts',
  'panel.dashboard.layoutModal.namePlaceholder': 'Layout name...',
  'panel.dashboard.layoutModal.save': 'Save',

  // --- Dashboard: per-widget chrome ---
  // Widget header icon-button tooltips (title=) and the body loading state.
  'panel.dashboard.widget.copyChart': 'Copy chart to clipboard',
  'panel.dashboard.widget.edit': 'Edit',
  'panel.dashboard.widget.refresh': 'Refresh',
  'panel.dashboard.widget.remove': 'Remove',
  'panel.dashboard.widget.loading': 'Loading…',

  // --- Report: chrome ---
  'panel.report.title': 'Saropa Drift Advisor Report',
  // {0} = generation timestamp, {1} = source server URL.
  'panel.report.generatedFrom': 'Generated {0} from {1}',
  'panel.report.toggleTheme': 'Toggle Theme',
  // {0} = generation timestamp.
  'panel.report.footer': 'Generated by Saropa Drift Advisor at {0}',

  // --- Report: per-table sidebar ---
  // {0} = pre-wrapped row-count badge markup; the truncated note is appended
  // separately only when the table's rows were cut off.
  'panel.report.table.truncated': '(truncated)',

  // --- Report: navigation tabs ---
  'panel.report.tab.data': 'Data',
  'panel.report.tab.schema': 'Schema',
  'panel.report.tab.anomalies': 'Anomalies',

  // --- Report: schema section ---
  'panel.report.schema.empty': 'No schema data available.',
  // Fallback table name when a schema entry has no usable table name.
  'panel.report.schema.unnamed': '(unnamed)',

  // --- Report: anomalies section ---
  'panel.report.anomalies.empty': 'No anomalies detected.',

  // --- Size Analytics: headings ---
  'panel.size.title': 'Database Size Analytics',
  'panel.size.tablesHeading': 'Tables by Row Count',

  // --- Size Analytics: summary cards ---
  'panel.size.card.total': 'Total Size',
  'panel.size.card.used': 'Used',
  'panel.size.card.free': 'Free',
  'panel.size.card.tables': 'Tables',
  // {0} = formatted byte size of one page (e.g. "Pages (4.0 KB each)").
  'panel.size.card.pages': 'Pages ({0} each)',
  'panel.size.card.journalMode': 'Journal Mode',
  // Shown in the index-name column when a table has no indexes.
  'panel.size.idx.none': 'none',

  // --- Size Analytics: table column headers ---
  'panel.size.col.table': 'Table',
  'panel.size.col.rows': 'Rows',
  'panel.size.col.cols': 'Cols',
  'panel.size.col.indexes': 'Indexes',
  'panel.size.col.indexNames': 'Index Names',

  // --- Size Analytics: footer actions ---
  'panel.size.btn.copyJson': 'Copy as JSON',
  'panel.size.btn.saveSnapshot': 'Save Snapshot',
  'panel.size.btn.compare': 'Compare',
  // {0} = history snapshot count, shown only when > 0 (e.g. "Compare (3)").
  'panel.size.btn.compareCount': 'Compare ({0})',

  // --- Profiler: heading / toolbar ---
  // {0} = numeric/text type label (see profiler.type.* below), shown after the
  // column's SQL type in the heading badge (e.g. "INTEGER (Numeric)").
  'panel.profiler.typeBadge': '{0} ({1})',
  'panel.profiler.type.numeric': 'Numeric',
  'panel.profiler.type.text': 'Text',
  'panel.profiler.btn.copyJson': 'Copy as JSON',

  // --- Profiler: summary cards ---
  'panel.profiler.card.totalRows': 'Total Rows',
  'panel.profiler.card.nonNull': 'Non-Null',
  'panel.profiler.card.null': 'Null',
  'panel.profiler.card.distinct': 'Distinct',

  // --- Profiler: numeric statistics ---
  'panel.profiler.numeric.heading': 'Numeric Statistics',
  'panel.profiler.numeric.min': 'Min',
  'panel.profiler.numeric.max': 'Max',
  'panel.profiler.numeric.mean': 'Mean',
  'panel.profiler.numeric.median': 'Median',
  'panel.profiler.numeric.stdDev': 'Std Dev',
  // Shown for median/std-dev when the statistic is unavailable.
  'panel.profiler.stat.na': 'N/A',

  // --- Profiler: text statistics ---
  'panel.profiler.text.heading': 'Text Statistics',
  'panel.profiler.text.minLength': 'Min Length',
  'panel.profiler.text.maxLength': 'Max Length',
  'panel.profiler.text.avgLength': 'Avg Length',
  'panel.profiler.text.emptyStrings': 'Empty Strings',

  // --- Profiler: histograms / tables ---
  'panel.profiler.histogram.valueDistribution': 'Value Distribution',
  'panel.profiler.histogram.lengthDistribution': 'Length Distribution',
  'panel.profiler.topValues.heading': 'Top Values',
  'panel.profiler.topValues.col.value': 'Value',
  'panel.profiler.topValues.col.count': 'Count',
  'panel.profiler.patterns.heading': 'Pattern Breakdown',
  'panel.profiler.patterns.col.pattern': 'Pattern',
  'panel.profiler.patterns.col.count': 'Count',
  'panel.profiler.anomalies.heading': 'Anomalies',

  // --- Perf baselines: empty / chrome ---
  'panel.perf.empty': 'No performance baselines stored.',
  'panel.perf.title': 'Performance Baselines',
  'panel.perf.btn.resetAll': 'Reset All',
  // {0} = number of stored baselines (e.g. "3 baseline(s) stored, ...").
  'panel.perf.summary':
    '{0} baseline(s) stored, sorted by avg duration (slowest first)',

  // --- Perf baselines: table headers / actions ---
  'panel.perf.col.sqlPattern': 'SQL Pattern',
  'panel.perf.col.avgDuration': 'Avg Duration',
  'panel.perf.col.samples': 'Samples',
  'panel.perf.col.lastUpdated': 'Last Updated',
  'panel.perf.btn.reset': 'Reset',
  // title= tooltip on each per-row reset button.
  'panel.perf.resetOne.tooltip': 'Reset this baseline',
};
