import type { IDocTable, ISchemaDocsData } from './schema-docs-types';
import { escapeHtml } from '../shared-utils';
import { getStandaloneTokens } from '../views/design-tokens';

/** Renders schema documentation as a self-contained HTML page. */
export class DocsHtmlRenderer {
  render(data: ISchemaDocsData): string {
    const toc = data.tables
      .map(
        t =>
          `<li><a href="#${esc(t.name)}">${esc(t.name)}</a>` +
          ` (${t.rowCount.toLocaleString()} rows)</li>`,
      )
      .join('\n      ');

    const diagram = data.diagramSvg
      ? `<section class="diagram">
    <h2>ER Diagram</h2>
    ${data.diagramSvg}
  </section>`
      : '';

    const tables = data.tables
      .map(t => this._renderTable(t))
      .join('\n  <hr>\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Schema Documentation</title>
  <style>${this._css()}</style>
</head>
<body>
  <header>
    <h1>Database Schema Documentation</h1>
    <p class="meta">Generated: ${esc(data.generatedAt)}
      | Tables: ${data.tables.length}
      | Rows: ${data.totalRows.toLocaleString()}
      | FKs: ${data.totalFks}</p>
  </header>

  <nav>
    <h2>Table of Contents</h2>
    <ul>
      ${toc}
    </ul>
  </nav>

  ${diagram}

  ${tables}

  <footer>
    <p>Generated by
      <a href="https://pub.dev/packages/saropa_drift_advisor"
        >Saropa Drift Advisor</a></p>
  </footer>
</body>
</html>`;
  }

  private _renderTable(table: IDocTable): string {
    const rows = table.columns
      .map(
        c =>
          `<tr>
        <td><code>${esc(c.name)}</code></td>
        <td>${esc(c.type)}</td>
        <td>${c.pk ? '\u2713' : ''}</td>
        <td>${c.fk ? `\u2192 ${esc(c.fk.toTable)}.${esc(c.fk.toColumn)}` : ''}</td>
        <td>${esc(c.description)}</td>
      </tr>`,
      )
      .join('\n      ');

    const refs =
      table.referencedBy.length > 0
        ? `<p><strong>Referenced by:</strong> ${table.referencedBy.map(r => `${esc(r.fromTable)}.${esc(r.fromColumn)}`).join(', ')}</p>`
        : '';

    return `<section id="${esc(table.name)}">
    <h2>${esc(table.name)}</h2>
    <p class="description">${esc(table.description)}</p>
    <table>
      <thead>
        <tr>
          <th>Column</th><th>Type</th><th>PK</th>
          <th>FK</th><th>Description</th>
        </tr>
      </thead>
      <tbody>
      ${rows}
      </tbody>
    </table>
    ${refs}
    <p><strong>Row count:</strong> ${table.rowCount.toLocaleString()}</p>
  </section>`;
  }

  private _css(): string {
    // Standalone exported doc has no host theme to inherit, so it ships the
    // canonical Saropa brand fallback palette (getStandaloneTokens) — same names
    // the report export uses — instead of a hand-painted indigo light palette
    // that ignored dark mode. The token block carries a prefers-color-scheme
    // dark override, so the exported doc now follows the reader's OS theme.
    return `
    ${getStandaloneTokens()}
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI',
        Roboto, Oxygen, sans-serif;
      max-width: 960px; margin: 2rem auto; padding: 0 1rem;
      color: var(--text); background: var(--surface-0);
    }
    header { margin-bottom: 2rem; }
    h1 { font-size: 1.8rem; margin-bottom: 0.25rem; }
    .meta { color: var(--muted); font-size: 0.9rem; }
    nav ul {
      list-style: none; display: flex; flex-wrap: wrap; gap: 0.5rem;
    }
    nav a {
      padding: 0.25rem 0.5rem; border-radius: var(--radius-sm);
      background: var(--surface-2); text-decoration: none; color: var(--link);
    }
    nav a:hover { background: var(--surface-3); }
    section { margin: 1.5rem 0; }
    h2 { font-size: 1.3rem; margin-bottom: 0.5rem; color: var(--brand-2); }
    .description { margin-bottom: 0.75rem; color: var(--muted); }
    table {
      width: 100%; border-collapse: collapse; margin-bottom: 0.5rem;
    }
    th, td {
      padding: 0.4rem 0.6rem; border: 1px solid var(--border);
      text-align: left; font-size: 0.9rem;
    }
    th { background: var(--surface-2); }
    tr:nth-child(even) { background: var(--surface-2); }
    code { font-family: 'Fira Code', monospace; font-size: 0.85rem; }
    hr { border: none; border-top: 1px solid var(--border); margin: 1.5rem 0; }
    footer {
      margin-top: 3rem; padding-top: 1rem;
      border-top: 1px solid var(--border); color: var(--muted); font-size: 0.8rem;
    }
    .diagram svg { max-width: 100%; height: auto; }
    `;
  }
}

/** Escape HTML entities. */
const esc = escapeHtml;
