import type { Anomaly } from '../api-types';
import type { IReportData, IReportSchema } from './report-types';
import { getReportCss } from './report-css';
import { getReportJs } from './report-scripts';

/** Build a complete self-contained HTML report from collected data. */
export function buildReportHtml(data: IReportData): string {
  const sidebarHtml = data.tables.map((t) =>
    `<button class="table-btn" data-table="${esc(t.name)}" onclick="showTable('${esc(escJs(t.name))}')">`
    + `${esc(t.name)} <span class="badge">${t.totalRowCount}</span>`
    + `${t.truncated ? ' <span class="truncated">(truncated)</span>' : ''}`
    + `</button>`,
  ).join('\n      ');

  const hasTabs = !!(data.schema || data.anomalies);
  const tabsHtml = hasTabs ? buildNavTabs(data) : '';
  const schemaHtml = data.schema ? buildSchemaSection(data.schema) : '';
  const anomalyHtml = data.anomalies ? buildAnomalySection(data.anomalies) : '';

  const tableDataJson = safeJsonForScript(data.tables.map((t) => ({
    name: t.name,
    columns: t.columns,
    rows: t.rows,
    totalRowCount: t.totalRowCount,
    truncated: t.truncated,
  })));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Saropa Drift Advisor Report</title>
<style>${getReportCss()}</style>
</head>
<body>
<div id="app">
  <header>
    <h1>Saropa Drift Advisor Report</h1>
    <div class="header-actions">
      <span class="generated">Generated ${esc(data.generatedAt)} from ${esc(data.serverUrl)}</span>
      <button class="theme-btn" onclick="toggleTheme()">Toggle Theme</button>
    </div>
  </header>

  <div class="layout">
    <nav class="sidebar">
      ${sidebarHtml}
    </nav>
    <main>
      ${tabsHtml}
      <div id="section-data"><div id="table-view"></div></div>
      ${schemaHtml}
      ${anomalyHtml}
    </main>
  </div>

  <footer>Generated by Saropa Drift Advisor at ${esc(data.generatedAt)}</footer>
</div>

<script>
var DATA = ${tableDataJson};
${getReportJs()}
</script>
</body>
</html>`;
}

function buildNavTabs(data: IReportData): string {
  let html = '<div class="nav-tabs">';
  html += '<button class="nav-tab active" data-section="data" onclick="showSection(\'data\')">Data</button>';
  if (data.schema) {
    html += '<button class="nav-tab" data-section="schema" onclick="showSection(\'schema\')">Schema</button>';
  }
  if (data.anomalies) {
    html += '<button class="nav-tab" data-section="anomalies" onclick="showSection(\'anomalies\')">Anomalies</button>';
  }
  html += '</div>';
  return html;
}

function buildSchemaSection(schemas: IReportSchema[]): string {
  if (schemas.length === 0) {
    return '<div id="section-schema" style="display:none"><p class="empty">No schema data available.</p></div>';
  }
  const items = schemas.map((s) =>
    `<div class="schema-item"><h3>${esc(s.table)}</h3><pre><code>${esc(s.sql)}</code></pre></div>`,
  ).join('\n');
  return `<div id="section-schema" style="display:none">${items}</div>`;
}

function buildAnomalySection(anomalies: Anomaly[]): string {
  if (anomalies.length === 0) {
    return '<div id="section-anomalies" style="display:none"><p class="empty">No anomalies detected.</p></div>';
  }
  const items = anomalies.map((a) => {
    const icon = a.severity === 'error' ? '\u2716' : a.severity === 'warning' ? '\u26A0' : '\u2139';
    return `<div class="anomaly anomaly-${esc(a.severity)}"><span class="anomaly-icon">${icon}</span>${esc(a.message)}</div>`;
  }).join('\n');
  return `<div id="section-anomalies" style="display:none">${items}</div>`;
}

/** Escape HTML special characters. */
function esc(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Escape a string for embedding in a JavaScript string literal within onclick. */
function escJs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/** Safely serialize a value as JSON for embedding inside a &lt;script&gt; tag. */
function safeJsonForScript(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e');
}
