# -*- coding: utf-8 -*-
"""Web viewer assets: build SCSS → CSS and enforce that built files match source.

The canonical source for styles is assets/web/style.scss; style.css must be
generated by `npm run build:style`. This module ensures the committed
style.css matches the build output so that only .scss (and in future .ts)
are edited, not the compiled artifacts.
"""

from __future__ import annotations

import os
import tempfile

from modules.constants import REPO_ROOT
from modules.display import fail, info, ok
from modules.utils import run


ASSETS_WEB = os.path.join(REPO_ROOT, "assets", "web")
STYLE_SCSS = os.path.join(ASSETS_WEB, "style.scss")
STYLE_CSS = os.path.join(ASSETS_WEB, "style.css")


def build_web_assets() -> bool:
    """Run npm install and npm run build:style. Overwrites assets/web/style.css.
    Use in CI so the tree has the built file; then git diff can enforce sync.
    Returns True on success.
    """
    if not os.path.isfile(STYLE_SCSS):
        ok("No style.scss (web assets build skipped)")
        return True
    info("Running: npm install")
    r = run(["npm", "install"], cwd=REPO_ROOT)
    if r.returncode != 0:
        fail("npm install failed")
        return False
    info("Running: npm run build:style")
    r = run(["npm", "run", "build:style"], cwd=REPO_ROOT)
    if r.returncode != 0:
        fail("npm run build:style failed")
        if r.stderr:
            info(r.stderr.strip())
        return False
    ok("Web assets built (style.scss → style.css)")
    return True


def check_web_assets_sync() -> bool:
    """Verify that assets/web/style.css matches the output of building style.scss.

    Builds style.scss to a temp file and compares with the committed style.css.
    Fails if they differ so that only source (.scss) is edited and build is run.
    """
    if not os.path.isfile(STYLE_SCSS):
        return True
    if not os.path.isfile(STYLE_CSS):
        fail("assets/web/style.css missing; run: npm run build:style")
        return False
    # Run sass to a temp file (same args as build:style).
    with tempfile.NamedTemporaryFile(
        mode="wb", suffix=".css", delete=False
    ) as f:
        tmp = f.name
    try:
        r = run(
            [
                "npx", "sass", STYLE_SCSS, tmp,
                "--no-source-map",
            ],
            cwd=REPO_ROOT,
        )
        if r.returncode != 0:
            fail("sass failed during sync check")
            return False
        with open(tmp, "rb") as f:
            built = f.read()
        with open(STYLE_CSS, "rb") as f:
            committed = f.read()
        if built != committed:
            fail(
                "assets/web/style.css is out of sync with style.scss. "
                "Edit only style.scss, then run: npm run build:style"
            )
            info("Commit the updated style.css after building.")
            return False
        ok("Web assets in sync (style.css matches style.scss)")
        return True
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def ensure_web_assets_sync() -> bool:
    """Ensure style.css is in sync with style.scss; if not, build and re-verify.

    When the sync check fails, runs npm run build:style to regenerate
    assets/web/style.css, then re-runs the sync check. The updated style.css
    will be included in the release commit when the pipeline runs Git commit & push.
    Returns True if in sync (or after a successful auto-build).
    """
    if check_web_assets_sync():
        return True
    info("Building style.scss → style.css...")
    if not build_web_assets():
        return False
    return check_web_assets_sync()
