/**
 * Generates Dart migration source from rollback SQL statements.
 * Follows the same format as migration-codegen.ts generateMigrationDart().
 */

export function generateDartFromSql(
  sql: string[],
  fromGeneration: number,
  toGeneration: number,
): string {
  const lines: string[] = [];

  lines.push("import 'package:drift/drift.dart';");
  lines.push('');
  lines.push(
    `// Rollback migration: undo schema changes from`
    + ` generation ${fromGeneration} to ${toGeneration}`,
  );
  lines.push('// Generated by Saropa Drift Advisor — review before using!');
  lines.push('');

  for (const stmt of sql) {
    if (stmt.startsWith('--')) {
      lines.push(`// ${stmt.slice(3).trim()}`);
    } else if (stmt.includes('\n')) {
      lines.push("await customStatement('''");
      lines.push(`  ${stmt}`);
      lines.push("''');");
    } else {
      const escaped = stmt.replace(/'/g, "\\'");
      lines.push('await customStatement(');
      lines.push(`  '${escaped}',`);
      lines.push(');');
    }
    lines.push('');
  }

  return lines.join('\n');
}
